name: beauty_master
description: "Professional mobile app for beauty and wellness masters"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Functional Programming
  dartz: ^0.10.1

  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3

  # HTTP & Network
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # UI & Images
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9

  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets (пока закомментированы)
  # assets:
  #   - assets/images/
  #   - assets/icons/
